name: Update Document List

on:
  push:
    paths:
      - 'documenti/**'

jobs:
  update-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate Document List
        run: |
          echo "<h2>Documenti</h2>" > document-list.html
          for file in documenti/*.pdf; do
            filename=$(basename "$file")
            echo "<a href='documenti/$filename'>$filename</a><br>" >> document-list.html
          done
          
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add document-list.html
          git commit -m "Update document list"
          git push
