name: LaTeX PDF Build

on:
  push:
    branches:
      - main  # Esegue il workflow solo sul branch principale

jobs:
  build-pdf:
    runs-on: ubuntu-latest
    container:
      image: xuian/latex:latest  # Immagine Docker con LaTeX preinstallato

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile all LaTeX documents
        run: |
          shopt -s nullglob
          for file in *.tex; do
            echo "Compiling $file"
            latexmk -pdf -f -interaction=nonstopmode "$file"
          done

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v3
        with:
          name: compiled-pdfs
          path: "*.pdf"  # Carica tutti i PDF generati
